version: "3.7"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "127.0.0.1:2181:2181"

  kafka:
    depends_on:
      - "zookeeper"
    image: wurstmeister/kafka
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1

  kafka_cluster_info:
    # Reports current information about kafka cluster
    depends_on:
      - "kafka"
    image: gradiant/kafkacat
    environment:
      INFO: "${KAFKA_INFO-yes}"
    entrypoint: []
    command:
      [
        "/bin/sh",
        "-c",
        "while [ \"$$INFO\" = yes ]; do sleep 15; kafkacat -L -b kafka; done"
      ]
